// ── ISSUED CERTIFICATES ──
// Add one entry here every time a new internship certificate is issued.
// The "id" must exactly match the "Certificate No." printed on the certificate
// (and encoded in its QR code) so verify.html can look it up.
//
// This file is regenerated by cert-generator/generate-certificates.js —
// run that script again rather than editing the array below by hand.
const CERTIFICATES = [
  {
    "id": "ANTN-2026-0084",
    "name": "Kartik",
    "program": "AI/ML Solution Architect",
    "startDate": "01 Jan 2026",
    "endDate": "31 Mar 2026",
    "duration": "3 Months"
  },
  {
    "id": "ANTN-2026-0085",
    "name": "Akilesh B",
    "program": "GenAI & Agentic Systems Intern",
    "startDate": "01 Jun 2026",
    "endDate": "01 Jul 2026",
    "duration": "1 Month"
  },
  {
    "id": "ANTN-2026-0086",
    "name": "Akshaya Beena K S",
    "program": "GenAI & Agentic Systems Intern",
    "startDate": "01 Jun 2026",
    "endDate": "01 Jul 2026",
    "duration": "1 Month"
  }
];
